#!/bin/bash
sudo docker run --rm -it -v $(eval echo "~$SUDO_USER")/.aws:/opt/app-root/src/.aws  \
  -v $(eval echo "~$SUDO_USER")/.osdd:/opt/app-root/src/.osdd \
  -v /:/host \
  --privileged -u 0 -t osdd
